"""Core domain primitives for the H0 model railway controller.

The package deliberately contains no transport, persistence, HTTP, UI, or
hardware code.  Higher-level services can compose these types to control a
real Z21 layout or a simulator.
"""

from .events import (
    BlockStateChanged,
    Event,
    EventController,
    EventSubscription,
    FeedbackHealthChanged,
    LayoutChanged,
    RouteChanged,
    ScheduleStateChanged,
    SignalAspectChanged,
    TrackPowerChanged,
    TrainDatabaseChanged,
    TrainModeChanged,
    TrainPositionChanged,
    TrainSpeedChanged,
    TurnoutPositionChanged,
)
from .graph import (
    GraphBuildError,
    GraphEdge,
    GraphNode,
    GraphNodeKind,
    LayoutGraph,
    LayoutGraphBuilder,
)
from .layout_controller import LayoutController
from .models import (
    Block,
    BlockState,
    LayoutSnapshot,
    Platform,
    PhotoScan,
    Point,
    RouteDefinition,
    Schedule,
    ScheduleStatus,
    ScheduleStop,
    Signal,
    SignalAspect,
    Station,
    Train,
    TrainMode,
    TrainModelInfo,
    TrainStatus,
    Turnout,
    TurnoutPosition,
    Turntable,
    Waypoint,
)
from .routing import (
    Route,
    RouteAlgorithm,
    a_star,
    breadth_first_search,
    find_route,
)
from .state import (
    StateController,
    StateSubscription,
    StateVersionConflict,
    VersionedSnapshot,
)

__all__ = [
    "Block",
    "BlockState",
    "BlockStateChanged",
    "Event",
    "EventController",
    "EventSubscription",
    "FeedbackHealthChanged",
    "GraphBuildError",
    "GraphEdge",
    "GraphNode",
    "GraphNodeKind",
    "LayoutChanged",
    "RouteChanged",
    "LayoutController",
    "LayoutGraph",
    "LayoutGraphBuilder",
    "LayoutSnapshot",
    "Platform",
    "PhotoScan",
    "Point",
    "Route",
    "RouteDefinition",
    "RouteAlgorithm",
    "Schedule",
    "ScheduleStateChanged",
    "ScheduleStatus",
    "ScheduleStop",
    "Signal",
    "SignalAspect",
    "SignalAspectChanged",
    "TrackPowerChanged",
    "TrainDatabaseChanged",
    "TrainModeChanged",
    "StateController",
    "StateSubscription",
    "StateVersionConflict",
    "Station",
    "Train",
    "TrainMode",
    "TrainModelInfo",
    "TrainPositionChanged",
    "TrainSpeedChanged",
    "TrainStatus",
    "Turnout",
    "TurnoutPosition",
    "TurnoutPositionChanged",
    "Turntable",
    "VersionedSnapshot",
    "Waypoint",
    "a_star",
    "breadth_first_search",
    "find_route",
]
