/* Isolated simulated controller: never connects to physical hardware. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawn } = require('node:child_process');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'h0-interactions-'));
let server, browser;
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
(async () => {
  server = spawn(process.env.PYTHON || 'python', ['-u', '-c', 'from backend.api.server import ControllerApplication, make_server; import sys; app=ControllerApplication.sample(database_path=sys.argv[1]); server=make_server(port=0, application=app); print(server.server_port, flush=True); server.serve_forever()', path.join(scratch, 'test.sqlite3')], { cwd: path.resolve(__dirname, '..'), windowsHide: true });
  const port = await new Promise((resolve, reject) => { server.stdout.once('data', data => resolve(String(data).trim())); server.once('error', reject); server.once('exit', code => reject(new Error(`Server exited ${code}`))); });
  browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'chrome' });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
  const errors = [], commands = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.url().endsWith('/api/commands') && request.method() === 'POST') commands.push(request.postDataJSON()); });
  await page.goto(`http://127.0.0.1:${port}`);
  await page.waitForFunction(() => document.querySelector('#sync-message').textContent.includes('online'));
  await page.locator('[data-workspace="layout"]').click();
  await page.locator('.block-node').first().dblclick();
  assert.equal(await page.locator('#block-editor').evaluate(node => node.open), true, 'Double-click opens editor');
  await page.locator('#cancel-block-editor').click();
  await page.locator('[data-workspace="trains"]').click();
  assert.equal(await page.locator('.editor-tab.is-active').getAttribute('data-editor-tab'), 'datasheet');
  assert.equal(await page.locator('.editor-tab').first().textContent(), 'Data sheet');
  await page.locator('.train-row').filter({ hasText: 'ICE 3' }).click();
  const dial = async (value, release = false) => page.locator('#speed-slider').evaluate((node, { value, release }) => { node.value = String(value); node.dispatchEvent(new Event('input', { bubbles: true })); if (release) node.dispatchEvent(new Event('change', { bubbles: true })); }, { value, release });
  await dial(12); await dial(28); await dial(43);
  await page.waitForRequest(request => request.url().endsWith('/api/commands') && request.postDataJSON()?.speed_kmh === 43);
  await pause(200);
  assert.deepEqual(commands.filter(command => command.type === 'set_speed').map(command => command.speed_kmh), [43], 'Debounce sends only last dial value');
  assert.equal(await page.locator('#direction-reverse').isDisabled(), true, 'Moving direction remains locked');
  const before = commands.length;
  await dial(77);
  await page.locator('.train-row').filter({ hasNotText: 'ICE 3' }).first().click();
  await pause(400);
  assert.equal(commands.slice(before).some(command => command.type === 'set_speed'), false, 'Selection cancels pending speed');
  await page.locator('.train-row').filter({ hasText: 'ICE 3' }).click();
  assert.equal(await page.locator('#speed-slider').inputValue(), '77', 'Dial remembers last selected value without resending');
  await dial(62);
  const stopRequest = page.waitForRequest(request => request.url().endsWith('/api/commands') && request.postDataJSON()?.type === 'stop_train');
  await page.locator('#stop-train').click();
  await stopRequest;
  await pause(500);
  assert.equal(commands.at(-1).type, 'stop_train', 'Stop replaces pending input');
  assert.equal(commands.some(command => command.type === 'set_speed' && command.speed_kmh === 62), false);
  await page.locator('[data-editor-tab="settings"]').click();
  await dial(58);
  await page.locator('#editor-control-mode').selectOption('automatic');
  await pause(400);
  assert.equal(commands.some(command => command.speed_kmh === 58), false, 'Mode change cancels pending input');
  await page.locator('[data-workspace="settings"]').click();
  assert.equal(await page.locator('#settings-connect-z21').isDisabled(), true, 'Browser has no native bridge');
  await page.evaluate(() => { window.pywebview = { api: { switch_mode: async mode => ({ accepted: false, error: `Test cancellation: ${mode}` }) } }; window.dispatchEvent(new Event('pywebviewready')); });
  await page.locator('#settings-connect-z21').click();
  await page.waitForFunction(() => document.querySelector('#settings-native-status').textContent === 'Test cancellation: z21');
  assert.deepEqual(errors, []);
  await page.locator('[data-workspace="layout"]').click();
  await page.locator('#connection-from').selectOption('b01');
  await page.locator('#connection-to').selectOption('b02');
  await page.locator('#connection-limit-speed').fill('40');
  await page.locator('#save-connection-limit').click();
  await page.waitForFunction(() => document.querySelector('#connection-limit-status').textContent.startsWith('Limit applied'));
  await page.locator('#connection-limit-train').selectOption('t1');
  await page.locator('#connection-limit-speed').fill('25');
  await page.locator('#save-connection-limit').click();
  await page.waitForFunction(() => document.querySelector('#connection-limit-status').textContent.startsWith('Limit applied'));
  let snapshot = await (await page.request.get(`http://127.0.0.1:${port}/api/state`)).json();
  assert.equal(snapshot.layout.connections.find(edge => edge.from === 'b01' && edge.to === 'b02').train_speed_limits.t1, 25);
  await page.locator('#connection-limit-speed').fill('');
  await page.locator('#save-connection-limit').click();
  await page.waitForFunction(() => document.querySelector('#connection-limit-status').textContent.startsWith('Limit applied'));
  snapshot = await (await page.request.get(`http://127.0.0.1:${port}/api/state`)).json();
  assert.equal(snapshot.layout.connections.find(edge => edge.from === 'b01' && edge.to === 'b02').train_speed_limits.t1, undefined);
  await page.locator('#add-layout-block').click();
  await page.waitForFunction(() => document.querySelector('#block-count').textContent === '5');
  await page.locator('#layout-power-toggle').click();
  await page.waitForFunction(() => document.querySelector('#layout-power-toggle').textContent === 'Power on');
  await page.locator('#edit-selected-block').click();
  await page.locator('#block-id').fill('TEST-YARD');
  const renameResponse = page.waitForResponse(response => response.url().endsWith('/api/commands') && response.request().postDataJSON()?.type === 'update_block');
  await page.locator('#block-editor button[type="submit"]').click();
  const rename = await renameResponse;
  assert.equal(rename.ok(), true, await rename.text());
  await page.waitForFunction(() => !document.querySelector('#block-editor').open);
  // Fixed authoritative samples exercise extrapolation without relying on a
  // real-time race or ever claiming that hardware has precise position data.
  const motionPage = await browser.newPage();
  snapshot.track_power = true;
  snapshot.simulation.running = true;
  snapshot.trains = [{ ...snapshot.trains[0], position: 'B01', motion: { block_id: 'b01', from_block_id: 'b01', to_block_id: 'b02', position: .2, speed: .1, source: 'simulation', time_seconds: 10, tick_seconds: .1 } }];
  await motionPage.route('**/api/**', async route => {
    const endpoint = new URL(route.request().url()).pathname;
    const payloads = { '/api/state': snapshot, '/api/layout': snapshot.layout, '/api/trains': snapshot.trains, '/api/train-database': { trains: [] }, '/api/connection': snapshot.connection };
    if (endpoint in payloads) await route.fulfill({ json: payloads[endpoint] }); else await route.continue();
  });
  await motionPage.goto(`http://127.0.0.1:${port}/#layout`);
  const marker = motionPage.locator('[data-motion-train-id]').first();
  await motionPage.waitForFunction(() => document.querySelector('[data-motion-train-id]')?.dataset.progress);
  const initial = Number(await marker.getAttribute('data-progress'));
  await pause(350);
  assert.ok(Number(await marker.getAttribute('data-progress')) > initial, 'Marker interpolates from position and speed');
  await pause(2100);
  const bounded = await marker.getAttribute('data-progress');
  await motionPage.locator('#refresh-button').click();
  await pause(400);
  assert.equal(await marker.getAttribute('data-progress'), bounded, 'Identical sample cannot restart extrapolation');
  snapshot.connection = { ...snapshot.connection, simulated: false, connected: true, mode: 'z21' };
  snapshot.trains[0].motion = { ...snapshot.trains[0].motion, source: 'reported', position: null, speed: null };
  await motionPage.reload();
  await marker.waitFor();
  assert.equal(await marker.getAttribute('data-position-source'), 'reported');
  const reported = await marker.getAttribute('transform');
  await pause(400);
  assert.equal(await marker.getAttribute('transform'), reported, 'No fabricated hardware motion');
  assert.equal(await marker.getAttribute('data-estimated'), null);
  await motionPage.close();
  console.log('PASS: block double-click/rename, profile tabs, safe debounced speed, native bridge status, directed limits/inheritance, bounded motion and no fabricated hardware positions.');
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => {
  if (browser) await browser.close();
  if (server && server.exitCode === null) { const exited = new Promise(resolve => server.once('exit', resolve)); server.kill(); await exited; }
  if (path.dirname(scratch) === path.resolve(os.tmpdir()) && path.basename(scratch).startsWith('h0-interactions-')) fs.rmSync(scratch, { recursive: true, force: true });
});
